### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by ZeroTenFuras** [craumix/jmb-container#4]
Hello,
I'm trying to host bot using Portainer on Oracle Cloud Server and when trying to run Container i get `exec /jmb/docker-entrypoint.sh: exec format error`.

**Comment by soguertler** [comment]
Can you please provide the command you're running (or your compose file) for more context?

**Comment by ZeroTenFuras** [comment]
I've tried to add a container directly from docker hub, and adding stack using 

```
version: '2.2'

services:
  jmusicbot:
    image: craumix/jmusicbot
    container_name: jmusicbot
    restart: unless-stopped
    volumes:
     - ./config:/jmb/config
```
